// ui/src/components/ScheduleDialog.tsx
import { useEffect } from 'react'
import { useForm } from 'react-hook-form'
import * as Dialog from '@radix-ui/react-dialog'
import { X, AlertCircle } from 'lucide-react'
import { useCreateSchedule, useUpdateSchedule } from '@/api/hooks'
import type { TriggerDefinition } from '@/api/types'
import { Button } from '@/components/ui/button'
import { Spinner } from '@/components/ui/spinner'

interface Props {
  jobKey: string
  schedule: TriggerDefinition | null
  open: boolean
  onOpenChange: (open: boolean) => void
}

interface ScheduleForm {
  cron_expression: string
  timezone: string
  calendar: string
  window: string
  enabled: boolean
}

const inputCls =
  'w-full px-3 py-2 border border-border rounded-md text-sm bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-primary'

export function ScheduleDialog({ jobKey, schedule, open, onOpenChange }: Props) {
  const createSchedule = useCreateSchedule()
  const updateSchedule = useUpdateSchedule()
  const isEdit = schedule !== null
  const {
    register,
    handleSubmit,
    reset,
    formState: { errors },
  } = useForm<ScheduleForm>()

  useEffect(() => {
    if (open) {
      reset({
        cron_expression: schedule?.cron_expression ?? '',
        timezone: schedule?.timezone ?? '',
        calendar: schedule?.calendar ?? '',
        window: schedule?.window ?? '',
        enabled: schedule?.enabled ?? true,
      })
    }
  }, [open, schedule, reset])

  const pending = createSchedule.isPending || updateSchedule.isPending
  const error = createSchedule.error ?? updateSchedule.error

  async function onSubmit(data: ScheduleForm) {
    const cron = data.cron_expression.trim()
    const tz = data.timezone.trim()
    const cal = data.calendar.trim()
    const win = data.window.trim()

    if (isEdit && schedule) {
      await updateSchedule.mutateAsync({
        trigger_id: schedule.trigger_id,
        cron_expression: cron,
        timezone: tz === '' ? null : tz,
        calendar: cal === '' ? null : cal,
        window: win === '' ? null : win,
        enabled: data.enabled,
      })
    } else {
      await createSchedule.mutateAsync({
        job_key: jobKey,
        cron_expression: cron,
        timezone: tz === '' ? undefined : tz,
        calendar: cal === '' ? undefined : cal,
        window: win === '' ? undefined : win,
        enabled: data.enabled,
      })
    }
    onOpenChange(false)
  }

  return (
    <Dialog.Root open={open} onOpenChange={onOpenChange}>
      <Dialog.Portal>
        <Dialog.Overlay className="fixed inset-0 z-40 bg-black/40" />
        <Dialog.Content className="fixed left-1/2 top-1/2 z-50 w-full max-w-md -translate-x-1/2 -translate-y-1/2 rounded-lg border border-border bg-card p-6 shadow-xl">
          <div className="flex items-center justify-between mb-4">
            <Dialog.Title className="text-sm font-semibold">
              {isEdit ? 'Edit Schedule' : 'New Schedule'} — {jobKey}
            </Dialog.Title>
            <Dialog.Close
              aria-label="Close dialog"
              className="text-muted-foreground hover:text-foreground"
            >
              <X className="h-4 w-4" />
            </Dialog.Close>
          </div>
          <form onSubmit={handleSubmit(onSubmit)} className="space-y-3">
            <div>
              <label className="block text-xs text-muted-foreground mb-1">
                Cron expression
              </label>
              <input
                {...register('cron_expression', { required: 'Required' })}
                autoFocus
                placeholder="*/5 * * * *  or  every 5 minutes"
                className={`${inputCls} font-mono`}
              />
              {errors.cron_expression ? (
                <p className="text-xs text-destructive mt-1">{errors.cron_expression.message}</p>
              ) : (
                <p className="text-[11px] text-muted-foreground mt-1">
                  Standard 5-field cron or Croniq DSL shorthand (e.g. <code>every 5 minutes</code>).
                </p>
              )}
            </div>
            <div>
              <label className="block text-xs text-muted-foreground mb-1">
                Timezone
              </label>
              <input
                {...register('timezone')}
                placeholder="Europe/Berlin"
                className={inputCls}
              />
              <p className="text-[11px] text-muted-foreground mt-1">
                IANA timezone. Empty means UTC.
              </p>
            </div>
            <div>
              <label className="block text-xs text-muted-foreground mb-1">
                Calendar
              </label>
              <input
                {...register('calendar')}
                placeholder="eu-business-hours"
                className={inputCls}
              />
              <p className="text-[11px] text-muted-foreground mt-1">
                Calendar name to gate firing. Empty for no calendar.
              </p>
            </div>
            <div>
              <label className="block text-xs text-muted-foreground mb-1">
                Window
              </label>
              <input
                {...register('window')}
                placeholder="08:00-18:00"
                className={inputCls}
              />
              <p className="text-[11px] text-muted-foreground mt-1">
                Optional inline time window. Empty for always-on.
              </p>
            </div>
            <label className="flex items-center gap-2 text-xs">
              <input type="checkbox" {...register('enabled')} className="h-3.5 w-3.5" />
              Enabled
            </label>
            {error && (
              <p className="text-xs text-destructive flex items-center gap-1">
                <AlertCircle className="h-3.5 w-3.5" />
                {String(error)}
              </p>
            )}
            <div className="flex justify-end gap-2 pt-2">
              <Dialog.Close asChild>
                <Button variant="secondary" size="sm" type="button">Cancel</Button>
              </Dialog.Close>
              <Button type="submit" size="sm" disabled={pending}>
                {pending ? <><Spinner className="h-3.5 w-3.5" />Saving…</> : isEdit ? 'Save changes' : 'Create schedule'}
              </Button>
            </div>
          </form>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  )
}

// src/Croniq.Ui/src/app/features/schedules/components/schedule-dialog/schedule-dialog.component.ts
import { ChangeDetectionStrategy, Component, computed, input, linkedSignal, output } from '@angular/core';
import { Field, form, required, submit } from '@angular/forms/signals';
import { UpsertScheduleRequest } from '@croniq/api-schema';

interface ScheduleFormModel {
    triggerId: string;
    jobKey: string;
    cronExpression: string;
    description: string;
    enabled: boolean;
    startAtUtc: string | null;
    endAtUtc: string | null;
}

const getScheduleFormModel = (schedule?: UpsertScheduleRequest | null): ScheduleFormModel => {
    if (schedule) {
        return {
            triggerId: schedule.triggerId ?? '',
            jobKey: schedule.jobKey ?? '',
            cronExpression: schedule.cronExpression ?? '',
            description: schedule.description ?? '',
            enabled: schedule.enabled ?? true,
            startAtUtc: schedule.startAtUtc ?? null,
            endAtUtc: schedule.endAtUtc ?? null,
        };
    }
    return {
        triggerId: '',
        jobKey: '',
        cronExpression: '',
        description: '',
        enabled: true,
        startAtUtc: null,
        endAtUtc: null,
    };
}

@Component({
    selector: 'app-schedule-dialog',
    imports: [Field],
    templateUrl: './schedule-dialog.component.html',
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ScheduleDialogComponent {
    readonly schedule = input<UpsertScheduleRequest | null>(null);

    readonly save = output<UpsertScheduleRequest>();
    readonly closeDialog = output<void>();

    readonly isEditMode = computed(() => !!this.schedule());

    readonly model = linkedSignal(() => getScheduleFormModel(this.schedule()));

    readonly scheduleForm = form(this.model, (f) => {
        required(f.jobKey);
        required(f.cronExpression);
    });

    async onSubmit(event: SubmitEvent) {
        event.preventDefault();

        await submit(this.scheduleForm, async () => {
            const request = this.model();
            this.save.emit(request);
        });
    }

    onCancel() {
        this.closeDialog.emit();
    }
}

<div
  class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm"
  role="dialog"
  aria-modal="true"
>
  <div class="w-full max-w-lg rounded-xl border border-white/10 bg-surface shadow-2xl">
    <form (submit)="onSubmit($event)" novalidate>
      <!-- Header -->
      <div class="flex items-center justify-between border-b border-white/10 px-6 py-4">
        <div class="flex items-center gap-4">
          <h2 class="text-lg font-semibold text-white">
            {{ isEditMode() ? 'Edit Schedule' : 'Create Schedule' }}
          </h2>
        </div>
        <button type="button" (click)="onCancel()" class="text-muted hover:text-white">
          <span class="sr-only">Close</span>
          <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M6 18L18 6M6 6l12 12"
            />
          </svg>
        </button>
      </div>

      <!-- Body -->
      <div class="px-6 py-6">
        <div class="space-y-4">
          <!-- Job Key -->
          <div>
            <label for="jobKey" class="mb-1 block text-sm font-medium text-muted">Job Key</label>
            <input
              type="text"
              id="jobKey"
              [field]="scheduleForm.jobKey"
              class="w-full rounded-lg border border-white/10 bg-surface-alt px-3 py-2 text-sm text-white placeholder-muted focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent"
              placeholder="e.g. billing:invoice-generation"
            />
          </div>

          <!-- Cron Expression -->
          <div>
            <label for="cronExpression" class="mb-1 block text-sm font-medium text-muted"
              >Cron Expression</label
            >
            <input
              type="text"
              id="cronExpression"
              [field]="scheduleForm.cronExpression"
              class="w-full rounded-lg border border-white/10 bg-surface-alt px-3 py-2 text-sm text-white placeholder-muted focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent"
              placeholder="e.g. 0 0 * * *"
            />
            <p class="mt-1 text-xs text-muted">
              Standard cron syntax (min hour day month day-of-week)
            </p>
          </div>

          <!-- Description -->
          <div>
            <label for="description" class="mb-1 block text-sm font-medium text-muted"
              >Description</label
            >
            <textarea
              id="description"
              [field]="scheduleForm.description"
              rows="3"
              class="w-full rounded-lg border border-white/10 bg-surface-alt px-3 py-2 text-sm text-white placeholder-muted focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent"
              placeholder="Optional description..."
            ></textarea>
          </div>

          <!-- Enabled Toggle -->
          <div class="flex items-center gap-2">
            <input
              type="checkbox"
              id="enabled"
              [field]="scheduleForm.enabled"
              class="h-4 w-4 rounded border-white/10 bg-surface-alt text-accent focus:ring-accent"
            />
            <label for="enabled" class="text-sm font-medium text-white">Enabled</label>
          </div>

          <!-- Hidden Trigger ID for Edit Mode -->
          <input type="hidden" [field]="scheduleForm.triggerId" />
        </div>
      </div>

      <!-- Footer -->
      <div
        class="flex items-center justify-end gap-3 border-t border-white/10 px-6 py-4 bg-surface-alt/50 rounded-b-xl"
      >
        <button
          type="button"
          (click)="onCancel()"
          class="rounded-lg px-4 py-2 text-sm font-medium text-muted hover:bg-white/5 hover:text-white transition"
        >
          Cancel
        </button>
        <button
          type="submit"
          [disabled]="scheduleForm().invalid()"
          class="rounded-lg bg-accent px-4 py-2 text-sm font-semibold text-white transition hover:bg-accent-hover disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {{ isEditMode() ? 'Save Changes' : 'Create Schedule' }}
        </button>
      </div>
    </form>
  </div>
</div>
