// ui/app/components/CalendarRuleBuilder.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { formatCalendarRules, parseCalendarRules, type CalendarRulePayload } from '~/lib/croniq-dsl'

/**
 * Calendar rules, built rather than typed.
 *
 * The rules are formatted and parsed by `croniq-config` compiled to wasm — the
 * same crate the server loads a Croniqfile with. That is the point of the
 * exercise: a builder backed by its own hand-written parser would agree with
 * the server right up until the day it didn't, and the disagreement would show
 * up as a job that quietly fired on a holiday.
 *
 * Every rule type produces the same `args: string[]`, so the wasm call is one
 * call whatever the reader picked.
 */
const props = defineProps<{
  /** Starting rules. Parsed out of stored DSL by the form above. */
  initial?: CalendarRulePayload[]
}>()

const emit = defineEmits<{
  /** The formatted DSL, on every valid change. This is what gets saved. */
  change: [dsl: string]
  /** Diagnostics from the parse pass, or null when the rules are clean. */
  error: [message: string | null]
}>()

const RULE_TYPES = ['weekly', 'window', 'monthly', 'annual', 'timezone'] as const
type RuleType = (typeof RULE_TYPES)[number]

const RULE_TYPE_LABELS: Record<RuleType, string> = {
  weekly: 'Weekdays',
  window: 'Time window',
  monthly: 'Days of month',
  annual: 'Specific date',
  timezone: 'Timezone',
}

/** Beside the controls rather than in a tooltip: it stays put while you work. */
const RULE_TYPE_HINTS: Record<RuleType, string> = {
  weekly: 'Days when this rule applies.',
  window: "Hour range, read on the calendar's own timezone — not the job's.",
  monthly: 'Days of the month. "Last" means the last day, whatever its number.',
  annual: 'One date, without a year — it recurs every year.',
  timezone: 'IANA name, e.g. Europe/Berlin.',
}

const WEEKDAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] as const
const WEEKDAY_PRESETS = [
  { label: 'Weekdays', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'] },
  { label: 'Weekend', days: ['Sat', 'Sun'] },
  { label: 'Every day', days: [...WEEKDAYS] },
]

const ORDINALS = [...Array.from({ length: 31 }, (_, i) => String(i + 1)), 'last']
const MONTHLY_PRESETS = [
  { label: '1st', days: ['1'] },
  { label: '15th', days: ['15'] },
  { label: '1st + 15th', days: ['1', '15'] },
  { label: 'Last day', days: ['last'] },
]
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

/**
 * A copy, field by field.
 *
 * Not `structuredClone`: the seed comes back from wasm through
 * `serde_wasm_bindgen`, and those objects are not structured-cloneable —
 * cloning them throws and takes the whole component render with it. Copying
 * the three fields this type actually has is both safe and honest about what
 * is being carried across.
 */
function copyRules(source: CalendarRulePayload[]): CalendarRulePayload[] {
  return source.map((rule) => ({
    action: rule.action,
    rule_type: rule.rule_type,
    args: [...rule.args],
  }))
}

const rules = ref<CalendarRulePayload[]>(
  props.initial?.length
    ? copyRules(props.initial)
    : [
        { action: 'include', rule_type: 'weekly', args: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'] },
        { action: 'exclude', rule_type: 'annual', args: ['12-25'] },
      ],
)

const dsl = ref('')

/**
 * Format, then parse what was formatted.
 *
 * The format direction produces what gets saved. The parse pass back is what
 * catches a rule whose arguments are the wrong shape — an annual rule holding
 * words instead of MM-DD — before the reader presses save rather than after.
 */
let generation = 0
watch(
  rules,
  async (current) => {
    const mine = ++generation
    try {
      const formatted = await formatCalendarRules(current)
      if (mine !== generation) return
      dsl.value = formatted
      emit('change', formatted)
      const parsed = await parseCalendarRules(formatted)
      if (mine !== generation) return
      emit('error', parsed.ok ? null : parsed.diagnostics.join('\n'))
    } catch (caught) {
      if (mine !== generation) return
      emit('error', caught instanceof Error ? caught.message : String(caught))
    }
  },
  { deep: true, immediate: true },
)

function addRule() {
  rules.value.push({ action: 'include', rule_type: 'weekly', args: [] })
}

function removeRule(index: number) {
  rules.value.splice(index, 1)
}

function setType(index: number, type: string) {
  // Arguments are type-specific; carrying them across would render DSL that
  // looks plausible and means something else.
  rules.value[index] = { ...rules.value[index]!, rule_type: type, args: [] }
}

function toggleAction(index: number) {
  const rule = rules.value[index]!
  rule.action = rule.action === 'include' ? 'exclude' : 'include'
}

/* ─── weekly ─────────────────────────────────────────────────────────────── */

/** Stored days may be `Mon` or `monday`; one shape in, one shape out. */
function normaliseDay(value: string): string | null {
  const match = WEEKDAYS.find((day) => day.toLowerCase() === value.toLowerCase().slice(0, 3))
  return match ?? null
}

function activeDays(rule: CalendarRulePayload): Set<string> {
  return new Set(rule.args.map(normaliseDay).filter((day): day is string => day !== null))
}

function toggleDay(index: number, day: string) {
  const rule = rules.value[index]!
  const active = activeDays(rule)
  if (active.has(day)) active.delete(day)
  else active.add(day)
  rule.args = WEEKDAYS.filter((candidate) => active.has(candidate))
}

/* ─── window ─────────────────────────────────────────────────────────────── */

function setWindow(index: number, slot: 0 | 1, value: string) {
  const rule = rules.value[index]!
  const next: [string, string] = [rule.args[0] ?? '', rule.args[1] ?? '']
  next[slot] = value
  // Drop empties rather than emit a half-open window mid-edit.
  rule.args = next[0] || next[1] ? next.filter(Boolean) : []
}

/* ─── monthly ────────────────────────────────────────────────────────────── */

function activeOrdinals(rule: CalendarRulePayload): Set<string> {
  return new Set(rule.args.map((arg) => arg.replace(/^(\d+)(st|nd|rd|th)$/i, '$1').toLowerCase()))
}

function toggleOrdinal(index: number, ordinal: string) {
  const rule = rules.value[index]!
  const active = activeOrdinals(rule)
  const key = ordinal.toLowerCase()
  if (active.has(key)) active.delete(key)
  else active.add(key)
  // Stable order, `last` at the end — so the DSL does not churn between
  // renders and a diff of two saves means something.
  rule.args = [...active].sort((a, b) => {
    if (a === 'last') return 1
    if (b === 'last') return -1
    return Number.parseInt(a, 10) - Number.parseInt(b, 10)
  })
}

/* ─── annual ─────────────────────────────────────────────────────────────── */

function annualParts(rule: CalendarRulePayload): { month: number; day: number } {
  const match = /^(\d{1,2})-(\d{1,2})$/.exec(rule.args[0] ?? '')
  return match
    ? { month: Number.parseInt(match[1]!, 10), day: Number.parseInt(match[2]!, 10) }
    : { month: 0, day: 0 }
}

function setAnnual(index: number, month: number, day: number) {
  const rule = rules.value[index]!
  rule.args =
    month && day
      ? [`${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`]
      : []
}

const copied = ref(false)
async function copyDsl() {
  try {
    await navigator.clipboard.writeText(dsl.value)
    copied.value = true
    setTimeout(() => (copied.value = false), 1500)
  } catch {
    // The text is on screen and selectable.
  }
}

const typeItems = computed(() =>
  RULE_TYPES.map((type) => ({ label: `${RULE_TYPE_LABELS[type]} (${type})`, value: type })),
)
</script>

<template>
  <div class="flex flex-col gap-3">
    <div
      v-for="(rule, index) in rules"
      :key="index"
      class="flex flex-col gap-2 rounded-lg border border-default p-3"
    >
      <div class="flex items-center gap-2">
        <!-- A toggle rather than a dropdown: include adds days, exclude
             removes them, and +/− is how the rule reads aloud. -->
        <UButton
          v-tooltip="`${rule.action} — click to switch`"
          :icon="rule.action === 'include' ? 'i-lucide-plus' : 'i-lucide-minus'"
          :color="rule.action === 'include' ? 'success' : 'error'"
          variant="subtle"
          size="xs"
          :aria-label="`Rule ${index + 1} is ${rule.action} — switch it`"
          @click="toggleAction(index)"
        />
        <USelectMenu
          :model-value="rule.rule_type"
          :items="typeItems"
          value-key="value"
          size="xs"
          class="flex-1"
          :aria-label="`Rule ${index + 1} type`"
          @update:model-value="(value: string) => setType(index, value)"
        />
        <UButton
          icon="i-lucide-trash-2"
          color="error"
          variant="ghost"
          size="xs"
          :aria-label="`Remove rule ${index + 1}`"
          @click="removeRule(index)"
        />
      </div>

      <p class="text-xs text-muted">
        {{ RULE_TYPE_HINTS[rule.rule_type as RuleType] }}
      </p>

      <!-- weekly -->
      <div
        v-if="rule.rule_type === 'weekly'"
        class="flex flex-col gap-2"
      >
        <div class="grid grid-cols-7 gap-1">
          <UButton
            v-for="day in WEEKDAYS"
            :key="day"
            :variant="activeDays(rule).has(day) ? 'solid' : 'outline'"
            :color="activeDays(rule).has(day) ? 'primary' : 'neutral'"
            size="xs"
            class="justify-center font-mono"
            :aria-pressed="activeDays(rule).has(day)"
            @click="toggleDay(index, day)"
          >
            {{ day }}
          </UButton>
        </div>
        <div class="flex flex-wrap gap-2">
          <UButton
            v-for="preset in WEEKDAY_PRESETS"
            :key="preset.label"
            variant="link"
            color="neutral"
            size="xs"
            class="p-0"
            @click="rule.args = [...preset.days]"
          >
            {{ preset.label }}
          </UButton>
        </div>
      </div>

      <!-- window -->
      <div
        v-else-if="rule.rule_type === 'window'"
        class="flex items-center gap-2"
      >
        <UInput
          type="time"
          :model-value="rule.args[0] ?? ''"
          size="xs"
          class="w-28"
          aria-label="Window start"
          @update:model-value="(value: string) => setWindow(index, 0, value)"
        />
        <span class="text-xs text-muted">to</span>
        <UInput
          type="time"
          :model-value="rule.args[1] ?? ''"
          size="xs"
          class="w-28"
          aria-label="Window end"
          @update:model-value="(value: string) => setWindow(index, 1, value)"
        />
      </div>

      <!-- monthly -->
      <div
        v-else-if="rule.rule_type === 'monthly'"
        class="flex flex-col gap-2"
      >
        <div class="grid grid-cols-8 gap-1">
          <UButton
            v-for="ordinal in ORDINALS"
            :key="ordinal"
            :variant="activeOrdinals(rule).has(ordinal.toLowerCase()) ? 'solid' : 'outline'"
            :color="activeOrdinals(rule).has(ordinal.toLowerCase()) ? 'primary' : 'neutral'"
            size="xs"
            class="justify-center px-0 font-mono"
            :aria-pressed="activeOrdinals(rule).has(ordinal.toLowerCase())"
            @click="toggleOrdinal(index, ordinal)"
          >
            {{ ordinal }}
          </UButton>
        </div>
        <div class="flex flex-wrap gap-2">
          <UButton
            v-for="preset in MONTHLY_PRESETS"
            :key="preset.label"
            variant="link"
            color="neutral"
            size="xs"
            class="p-0"
            @click="rule.args = [...preset.days]"
          >
            {{ preset.label }}
          </UButton>
        </div>
      </div>

      <!-- annual -->
      <div
        v-else-if="rule.rule_type === 'annual'"
        class="flex items-center gap-2"
      >
        <USelectMenu
          :model-value="annualParts(rule).month || undefined"
          :items="MONTHS.map((label, i) => ({ label, value: i + 1 }))"
          value-key="value"
          size="xs"
          class="w-32"
          placeholder="Month…"
          aria-label="Month"
          @update:model-value="(value: number) => setAnnual(index, value, annualParts(rule).day)"
        />
        <UInput
          type="number"
          :min="1"
          :max="31"
          :model-value="annualParts(rule).day || ''"
          size="xs"
          class="w-20"
          placeholder="Day"
          aria-label="Day of month"
          @update:model-value="
            (value: string) => setAnnual(index, annualParts(rule).month, Number(value) || 0)
          "
        />
      </div>

      <!-- timezone -->
      <UInput
        v-else-if="rule.rule_type === 'timezone'"
        :model-value="rule.args[0] ?? ''"
        size="xs"
        class="font-mono"
        placeholder="Europe/Berlin"
        aria-label="Timezone"
        @update:model-value="(value: string) => (rule.args = value.trim() ? [value.trim()] : [])"
      />
    </div>

    <UButton
      icon="i-lucide-plus"
      variant="outline"
      color="neutral"
      size="xs"
      block
      class="border-dashed"
      @click="addRule"
    >
      Add rule
    </UButton>

    <div>
      <div class="mb-1 flex items-center justify-between">
        <p class="cq-label">
          Resulting DSL
        </p>
        <UButton
          v-if="dsl"
          :icon="copied ? 'i-lucide-check' : 'i-lucide-copy'"
          color="neutral"
          variant="ghost"
          size="xs"
          aria-label="Copy the calendar DSL"
          @click="copyDsl"
        />
      </div>
      <!-- `output` with a live region: the DSL changes as a consequence of
           what was just clicked, which is exactly what aria-live is for. -->
      <output
        class="block rounded-md border border-default bg-elevated p-2 font-mono text-xs break-words whitespace-pre-wrap"
        aria-live="polite"
      >{{ dsl || '—' }}</output>
    </div>
  </div>
</template>

// ui/src/components/builders/CalendarRuleBuilder.tsx
import { useEffect, useState } from 'react'
import { Trash2, Plus, Minus } from 'lucide-react'
import { formatCalendarRules, parseCalendarRules, type CalendarRulePayload } from '@/lib/croniq-dsl'
import { CopyButton } from '@/components/ui/copy-button'
import { TimezoneInput } from '@/components/ui/timezone-input'

const RULE_TYPES = ['weekly', 'window', 'monthly', 'annual', 'timezone'] as const

const RULE_TYPE_LABELS: Record<(typeof RULE_TYPES)[number], string> = {
  weekly: 'Weekdays',
  window: 'Time window',
  monthly: 'Days of month',
  annual: 'Specific date',
  timezone: 'Timezone',
}

// Per-rule-type one-line caption shown beside the rule editor. Less
// noisy than a tooltip, more discoverable than a placeholder, and
// stays put while the user fills in the structured controls.
const RULE_TYPE_HINTS: Record<(typeof RULE_TYPES)[number], string> = {
  weekly: 'Days when this rule applies.',
  window: "Hour range, read on the calendar's own timezone (below) — not the job's.",
  monthly: 'Days of month — pick numbers or "Last".',
  annual: 'A single calendar date (no year — fires every year on this day).',
  timezone: 'IANA name. Type to search; the browser picker filters as you type.',
}

const WEEKDAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] as const
const WEEKDAY_PRESETS: { label: string; days: (typeof WEEKDAYS)[number][] }[] = [
  { label: 'Weekday', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'] },
  { label: 'Weekend', days: ['Sat', 'Sun'] },
  { label: 'Every day', days: [...WEEKDAYS] },
]

const ORDINALS = [
  '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
  '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
  '21', '22', '23', '24', '25', '26', '27', '28', '29', '30',
  '31', 'last',
]
const MONTHLY_PRESETS: { label: string; days: string[] }[] = [
  { label: '1st', days: ['1'] },
  { label: '15th', days: ['15'] },
  { label: '1st + 15th', days: ['1', '15'] },
  { label: 'Last day', days: ['last'] },
]

const MONTHS = [
  'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
]

interface Props {
  /// Emitted whenever the form produces a valid DSL string. The dialog
  /// passes this through to the API on submit.
  onChange: (dsl: string) => void
  /// Surfaced parse errors — the dialog renders this inline so the user
  /// can fix the expression before submitting.
  onError?: (msg: string | null) => void
  /// Optional initial rule list. Defaults to the same Mon-Fri / no
  /// Christmas pair we ship in the standalone generator.
  initial?: CalendarRulePayload[]
}

const inputCls =
  'w-full px-3 py-2 border border-border rounded-md text-sm bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-primary'

const chipBase =
  'inline-flex items-center justify-center rounded-md text-xs font-mono transition-colors border'
const chipOff =
  'bg-background border-border text-muted-foreground hover:border-primary/50'
const chipOn =
  'bg-primary/15 border-primary text-primary'

export function CalendarRuleBuilder({ onChange, onError, initial }: Props) {
  const [rules, setRules] = useState<CalendarRulePayload[]>(
    initial ?? [
      { action: 'include', rule_type: 'weekly', args: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'] },
      { action: 'exclude', rule_type: 'annual', args: ['12-25'] },
    ],
  )
  const [dsl, setDsl] = useState('')

  // Format → parse round-trip on every change. The format direction is
  // the source of truth fed to the API; the parse pass lets us catch
  // malformed args (e.g. an annual rule with text instead of MM-DD)
  // before submit and surface them inline.
  useEffect(() => {
    let cancelled = false
    ;(async () => {
      try {
        const formatted = await formatCalendarRules(rules)
        if (cancelled) return
        setDsl(formatted)
        onChange(formatted)
        const parsed = await parseCalendarRules(formatted)
        if (cancelled) return
        if (!parsed.ok) onError?.(parsed.diagnostics.join('\n'))
        else onError?.(null)
      } catch (e) {
        if (cancelled) return
        onError?.(e instanceof Error ? e.message : String(e))
      }
    })()
    return () => {
      cancelled = true
    }
  }, [rules, onChange, onError])

  function updateRule(idx: number, patch: Partial<CalendarRulePayload>) {
    setRules((prev) => prev.map((r, i) => (i === idx ? { ...r, ...patch } : r)))
  }

  function removeRule(idx: number) {
    setRules((prev) => prev.filter((_, i) => i !== idx))
  }

  function addRule() {
    setRules((prev) => [...prev, { action: 'include', rule_type: 'weekly', args: [] }])
  }

  return (
    <div className="space-y-3">
      {rules.map((rule, idx) => (
        <div key={idx} className="rounded-md border border-border bg-background/50 p-3 space-y-2">
          <div className="flex items-center gap-2">
            {/* Compact toggle for include/exclude — the full-width
                <select> ate too much space next to the rule type. The
                "+"/"−" mirrors the way calendar rules read aloud
                (include adds days, exclude removes them) and the
                colour reinforces the semantics at a glance. */}
            <button
              type="button"
              onClick={() =>
                updateRule(idx, { action: rule.action === 'include' ? 'exclude' : 'include' })
              }
              aria-label={`Rule ${idx + 1} action: ${rule.action} (click to switch)`}
              title={`${rule.action} — click to switch`}
              className={`h-7 w-7 inline-flex items-center justify-center rounded-md border text-xs font-bold shrink-0 ${
                rule.action === 'include'
                  ? 'border-status-ok-fg/40 bg-status-ok-bg text-status-ok-fg'
                  : 'border-destructive/40 bg-destructive/10 text-destructive'
              }`}
            >
              {rule.action === 'include' ? <Plus className="h-3.5 w-3.5" /> : <Minus className="h-3.5 w-3.5" />}
            </button>
            <select
              value={rule.rule_type}
              onChange={(e) => {
                // Reset args when the rule type changes — they have
                // type-specific shape and a stale carry-over would
                // silently mis-render the DSL.
                updateRule(idx, { rule_type: e.target.value, args: [] })
              }}
              className={`${inputCls} py-1.5 text-xs flex-1`}
              aria-label={`Rule ${idx + 1} type`}
            >
              {RULE_TYPES.map((t) => (
                <option key={t} value={t}>
                  {RULE_TYPE_LABELS[t]} ({t})
                </option>
              ))}
            </select>
            <button
              type="button"
              onClick={() => removeRule(idx)}
              aria-label={`Remove rule ${idx + 1}`}
              className="h-7 w-7 inline-flex items-center justify-center rounded-md text-muted-foreground hover:text-destructive"
            >
              <Trash2 className="h-3.5 w-3.5" />
            </button>
          </div>
          <p className="text-[10px] text-muted-foreground leading-snug">
            {RULE_TYPE_HINTS[rule.rule_type as (typeof RULE_TYPES)[number]]}
          </p>
          <RuleEditor
            rule={rule}
            onChange={(args) => updateRule(idx, { args })}
          />
        </div>
      ))}
      <button
        type="button"
        onClick={addRule}
        className="w-full py-2 rounded-md border border-dashed border-border text-xs text-muted-foreground hover:text-primary hover:border-primary/50 inline-flex items-center justify-center gap-1.5"
      >
        <Plus className="h-3.5 w-3.5" />
        Add rule
      </button>
      <div>
        <div className="flex items-center justify-between mb-1">
          <label htmlFor="calendar-rule-builder-dsl" className="text-xs font-medium text-foreground">
            DSL
          </label>
          {dsl && <CopyButton value={dsl} label="Copy calendar DSL" />}
        </div>
        <output
          id="calendar-rule-builder-dsl"
          aria-live="polite"
          className="block text-xs bg-muted rounded-md p-2 font-mono whitespace-pre-wrap break-words"
        >
          {dsl || '(empty calendar — always on)'}
        </output>
      </div>
    </div>
  )
}

interface RuleEditorProps {
  rule: CalendarRulePayload
  onChange: (args: string[]) => void
}

/// Per-rule-type structured editor. Replaces the previous single-text
/// input — typing `mon..fri` worked but the calendar preview never
/// reacted, the args weren't validated until submit, and `weekly` /
/// `monthly` / `annual` shared one input shape that fit none of them
/// well. Each branch below produces the same `args: string[]` the
/// rest of the editor expects, so the WASM call site is unchanged.
function RuleEditor({ rule, onChange }: RuleEditorProps) {
  if (rule.rule_type === 'weekly') return <WeeklyEditor rule={rule} onChange={onChange} />
  if (rule.rule_type === 'window') return <WindowEditor rule={rule} onChange={onChange} />
  if (rule.rule_type === 'monthly') return <MonthlyEditor rule={rule} onChange={onChange} />
  if (rule.rule_type === 'annual') return <AnnualEditor rule={rule} onChange={onChange} />
  if (rule.rule_type === 'timezone') return <TimezoneEditor rule={rule} onChange={onChange} />
  return null
}

function WeeklyEditor({ rule, onChange }: RuleEditorProps) {
  // Stored args may be 3-letter (`Mon`) or full (`monday`); normalise
  // to 3-letter capitalised for both display and storage so the WASM
  // formatter sees a consistent shape it can collapse to `weekday` /
  // `Mon..Fri` / etc.
  const active = new Set(rule.args.map(normaliseDay).filter(Boolean) as string[])
  function toggle(day: string) {
    const next = new Set(active)
    if (next.has(day)) next.delete(day)
    else next.add(day)
    onChange([...WEEKDAYS].filter((d) => next.has(d)))
  }
  function applyPreset(days: readonly string[]) {
    onChange([...days])
  }
  return (
    <div className="space-y-2">
      <div className="grid grid-cols-7 gap-1">
        {WEEKDAYS.map((d) => {
          const on = active.has(d)
          return (
            <button
              key={d}
              type="button"
              onClick={() => toggle(d)}
              aria-pressed={on}
              className={`${chipBase} px-1 py-1.5 ${on ? chipOn : chipOff}`}
            >
              {d}
            </button>
          )
        })}
      </div>
      <div className="flex flex-wrap gap-1.5">
        {WEEKDAY_PRESETS.map((p) => (
          <button
            key={p.label}
            type="button"
            onClick={() => applyPreset(p.days)}
            className="text-[10px] uppercase tracking-wide text-muted-foreground hover:text-primary"
          >
            {p.label}
          </button>
        ))}
      </div>
    </div>
  )
}

function WindowEditor({ rule, onChange }: RuleEditorProps) {
  const [from, to] = [rule.args[0] ?? '', rule.args[1] ?? '']
  function set(idx: 0 | 1, value: string) {
    const next = [from, to] as [string, string]
    next[idx] = value
    // Drop trailing empty values so the formatter doesn't emit a half-
    // window like `"08:00".."` while the user is mid-edit.
    if (!next[0] && !next[1]) onChange([])
    else onChange(next.filter(Boolean))
  }
  return (
    <div className="flex items-center gap-2 text-xs">
      <input
        type="time"
        value={from}
        onChange={(e) => set(0, e.target.value)}
        aria-label="Window start (UTC)"
        className={`${inputCls} py-1.5 w-[100px]`}
      />
      <span className="text-muted-foreground">to</span>
      <input
        type="time"
        value={to}
        onChange={(e) => set(1, e.target.value)}
        aria-label="Window end (UTC)"
        className={`${inputCls} py-1.5 w-[100px]`}
      />
    </div>
  )
}

function MonthlyEditor({ rule, onChange }: RuleEditorProps) {
  const active = new Set(rule.args.map((a) => a.replace(/^(\d+)(st|nd|rd|th)$/i, '$1').toLowerCase()))
  function toggle(o: string) {
    const next = new Set(active)
    if (next.has(o)) next.delete(o)
    else next.add(o)
    // Sort numerics ascending and append `last` if present so the DSL
    // stays in a stable order between renders.
    const out = [...next]
      .sort((a, b) => {
        if (a === 'last') return 1
        if (b === 'last') return -1
        return parseInt(a, 10) - parseInt(b, 10)
      })
    onChange(out)
  }
  function applyPreset(days: string[]) {
    onChange([...days])
  }
  return (
    <div className="space-y-2">
      <div className="grid grid-cols-8 gap-1">
        {ORDINALS.map((o) => {
          const on = active.has(o.toLowerCase())
          return (
            <button
              key={o}
              type="button"
              onClick={() => toggle(o)}
              aria-pressed={on}
              className={`${chipBase} px-1 py-1 ${on ? chipOn : chipOff}`}
            >
              {o}
            </button>
          )
        })}
      </div>
      <div className="flex flex-wrap gap-1.5">
        {MONTHLY_PRESETS.map((p) => (
          <button
            key={p.label}
            type="button"
            onClick={() => applyPreset(p.days)}
            className="text-[10px] uppercase tracking-wide text-muted-foreground hover:text-primary"
          >
            {p.label}
          </button>
        ))}
      </div>
    </div>
  )
}

function AnnualEditor({ rule, onChange }: RuleEditorProps) {
  // Stored as a single MM-DD string. Split into separate month/day
  // controls so the user gets a labelled month dropdown + a numeric
  // day input instead of a free-form `12-25` text field. Empty rule
  // = empty args; we only emit the formatted string once both halves
  // are filled.
  const current = rule.args[0] ?? ''
  const m = /^(\d{1,2})-(\d{1,2})$/.exec(current)
  const month = m ? parseInt(m[1], 10) : 0
  const day = m ? parseInt(m[2], 10) : 0

  function emit(nextMonth: number, nextDay: number) {
    if (!nextMonth || !nextDay) {
      onChange([])
      return
    }
    const mm = String(nextMonth).padStart(2, '0')
    const dd = String(nextDay).padStart(2, '0')
    onChange([`${mm}-${dd}`])
  }
  return (
    <div className="flex items-center gap-2 text-xs">
      <select
        value={month}
        onChange={(e) => emit(parseInt(e.target.value, 10), day)}
        aria-label="Month"
        className={`${inputCls} py-1.5 text-xs w-[100px]`}
      >
        <option value={0}>Month…</option>
        {MONTHS.map((label, i) => (
          <option key={label} value={i + 1}>
            {label}
          </option>
        ))}
      </select>
      <input
        type="number"
        min={1}
        max={31}
        value={day || ''}
        placeholder="Day"
        onChange={(e) => emit(month, parseInt(e.target.value, 10) || 0)}
        aria-label="Day of month"
        className={`${inputCls} py-1.5 text-xs w-[80px]`}
      />
      {month > 0 && day > 0 && (
        <span className="text-muted-foreground tabular-nums">
          {MONTHS[month - 1]} {day}
        </span>
      )}
    </div>
  )
}

function TimezoneEditor({ rule, onChange }: RuleEditorProps) {
  // Same TimezoneInput the Schedule builder uses — typeahead over the
  // browser's full IANA list, with the detected default surfaced as a
  // hint while the input is empty.
  const value = rule.args[0] ?? ''
  return (
    <TimezoneInput
      defaultValue={value}
      onChange={(e) => {
        const v = e.currentTarget.value.trim()
        onChange(v ? [v] : [])
      }}
      onBlur={(e) => {
        const v = e.currentTarget.value.trim()
        onChange(v ? [v] : [])
      }}
      showDetectedHint={!value}
      className={`${inputCls} py-1.5 text-xs`}
    />
  )
}

/// Normalise a weekday token to its capitalised 3-letter form
/// (`Mon`, `Tue`, ..., `Sun`). Returns `null` if the input doesn't
/// look like a weekday — used to filter out garbage when the user
/// types into the Advanced (raw) tab and switches back.
function normaliseDay(s: string): string | null {
  const lower = s.toLowerCase().slice(0, 3)
  switch (lower) {
    case 'mon': return 'Mon'
    case 'tue': return 'Tue'
    case 'wed': return 'Wed'
    case 'thu': return 'Thu'
    case 'fri': return 'Fri'
    case 'sat': return 'Sat'
    case 'sun': return 'Sun'
    default: return null
  }
}
